### ISSUE TITLE
will_paginate gem dependency issue

### ISSUE THREAD

**Issue by tomfast** [jbarnette/isolate#31]
Has anyone had success getting will_paginate to work with Isolate and Rails 2.3.5? 

I have the following listed in my Isolate file:

gem "will_paginate", "2.3.11"

And I get the following error:
NoMethodError (undefined method `paginate' for #Class:0x104a8d068):

I've also tried using the will_paginate version 2.3.15 with no success.
